#!/bin/sh /etc/rc.common

START=91

NAME=dirtydns
PROG=/usr/bin/dirtydns
USE_PROCD=1

start_instance() {
  local port
  local ipset
  local dirty
  local secured

  config_get port "$1" port
  config_get ipset "$1" ipset_dirty
  config_get dirty "$1" dirty_upstream
  config_get secured "$1" secured_upstream

  procd_open_instance
  procd_set_param respawn
  procd_set_param command "$PROG $port $dirty $secured $ipset"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

service_triggers() {
  procd_add_reload_trigger $NAME
}

start_service() {
  config_load $NAME
  config_foreach start_instance server
}
